// Generated by CoffeeScript 1.8.0
define(function(require, exports, module) {
  "use strict";
  var module1;
  module1 = {};
  module1.init = function() {
    return console.log("module1 Init.");
  };
  return module.exports = module1;
});
