// Generated by CoffeeScript 1.8.0
define(function() {
  "use strict";
  var <%= appname %> = {};
  <%= appname %>.init = function(){
    console.log("<%= appname %> Init.");
  }
  return <%= appname %>;
});
