// Generated by CoffeeScript 1.8.0
define(function(require, module, exports) {
  "use strict";
  var <%= appname %> = {};
  <%= appname %>.init = function(){
    console.log("<%= appname %> Init.");
  }
  return module.exports = <%= appname %>;
});
